### ISSUE TITLE
kudo's

### ISSUE THREAD

**Issue by RobertLemmens** [pauljamescleary/scala-pet-store#3]
Just wanna leave some kudo's. "Real world", easy to read examples are somewhat scarce in the FP community. Allot of theoretical information is out there, but projects like these are whats missing imo. Seeing the knots tied together here shows me the real value of these FP constructs.

Thanks.

**Comment by pauljamescleary** [comment]
Thanks @RobertLemmens!  Always looking to take contributions if you have any ideas :)

I have a decent roadmap planned, including a vue js front end and validation.  I don't want to make it too big, just big enough.

Also, I maybe inspired to create a free monad version, as well as an eff version since I have interest there.  Those would be easier to complete once the initial version is complete.

**Comment by daddykotex** [comment]
Same thing for me, I'm writing an app myself using almost the same stack, and looking at your code is giving me lots of hints!

I saw in one of the file that you'd like to have flyway migrations to setup the database. I did it for postgres ( I know you use H2 ) if you need an example, here's the commit where I introduced it: https://github.com/daddykotex/subs/commit/836d7ceb8a21ba4185f92ba8ac82a6423fad1caa

**Comment by pauljamescleary** [comment]
@daddykotex Thanks!  I use flyway migrations regularly (I will create an Issue for that work here).  Will checkout what you have there

**Comment by pauljamescleary** [comment]
@daddykotex The one issue I found was that the sbt plugin just doesn't work when deploying to a real environment.  I had to create a little wrapper main around flyway to run migrations.

Not sure if you had better success with running it in production.

There was an issue I hit recently where the build.sbt conflicted with the jvm overrides.  Something like the flyway url or flyway user was different between where the `SCHEMA_VERSION` table is kept and the schema that you are managing is kept.  They should be in the same database but they somehow got messed up with sbt.

**Comment by daddykotex** [comment]
> The one issue I found was that the sbt plugin just doesn't work when deploying to a real environment.

Do you mean that when you deploy, you usually ship a jar(or docker) or something that can be ran and thus you don't have `sbt` or the whole project source (including migrations) to run the `flywayMigrate` command.

I can't say I had much more success in production because I did not do it, but I think that if I was to use it as part of a deployment process, I would trigger the `sbt` execution via `jenkins` (or any other CI I'll use).

Anyhow, I'll let you know how it goes 👍

**Comment by pauljamescleary** [comment]
@daddykotex I mean I ran `sbt flywayMigrate` and tried to pass in the command line arguments to override the jdbc url, user, password and such and it failed.  It wound up putting the `schema_version` table in my local H2 instance (that is setup in the build.sbt), and NOT in the target database.  

I kinda gave up and didn't look much into why to be honest.  It should be fixed, at least I should have created an issue.

But for me, it was easy enough to run flyway myself as the api is easy to do.
